export default {
    UM_CANIBAL: 'UM CANIBAL',
    UM_MISSIONARIO: 'UM MISSIONARIO',
    DOIS_CANIBAIS: 'DOIS CANIBAIS',
    DOIS_MISSIONARIOS: 'DOIS MISSIONARIOS',
    UM_CANIBAL_UM_MISSIONARIO: 'UM CANIBAL E UM MISSIONARIO'
};
